### ISSUE TITLE
Creates a brand for the company

### ISSUE THREAD

**Issue by greengrass17** [TranLe2403/SumWebPro#1]
We need a logo, a name, and color so the studio is recognizable for the players.

Acceptance criteria:
- Have a logo as an SVG image file
- Have a company name
- Choose the main color for the website
- Pick a few sample websites from the game companies listed here https://www.gamedevmap.com/index.php?location=Helsinki

**Comment by greengrass17** [comment]
- The cats: Napami, Pami Studio
- Lego block: Brick Studio

**Comment by TranLe2403** [comment]
Recycle studio

**Comment by greengrass17** [comment]
Final decision: LIFT studio

**Comment by TranLe2403** [comment]
![website_logo](https://user-images.githubusercontent.com/48984209/58045919-14608680-7b6e-11e9-9683-fb637926db03.png)

**Comment by greengrass17** [comment]
Final SVG version

https://storage.googleapis.com/lift-website-220519/lift-logo.svg
